import {
  Wallet,
  Coins,
  Laptop,
  CircleDollarSign,
  ShoppingCart,
  Shirt,
  Gamepad2,
  Car,
  Home,
  Receipt,
  CreditCard,
  Shield,
  Plane,
  PiggyBank,
  Landmark,
  TrendingUp,
  Utensils,
  Heart,
  Zap,
  Wifi,
  Smartphone,
  Book,
  GraduationCap,
  Stethoscope,
  Baby,
  Gift,
  Bus,
  Fuel,
  LucideIcon,
  Video,
  Banknote,
  Building2,
  Droplet,
  Flame,
} from 'lucide-react'
import { cn } from '@/lib/utils'

const iconMap: Record<string, LucideIcon> = {
  Wallet,
  Coins,
  Laptop,
  CircleDollarSign,
  ShoppingCart,
  Shirt,
  Gamepad2,
  Car,
  Home,
  Receipt,
  CreditCard,
  Shield,
  Plane,
  PiggyBank,
  Landmark,
  TrendingUp,
  Utensils,
  Heart,
  Zap,
  Wifi,
  Smartphone,
  Book,
  GraduationCap,
  Stethoscope,
  Baby,
  Gift,
  Bus,
  Fuel,
  Video,
  Banknote,
  Building2,
  Droplet,
  Flame,
}

/** Chaves Lucide (valor salvo) e rótulos em português (exibição). */
export const CATEGORY_ICON_OPTIONS = [
  { key: 'Wallet', label: 'Carteira' },
  { key: 'Coins', label: 'Moedas' },
  { key: 'Laptop', label: 'Notebook' },
  { key: 'CircleDollarSign', label: 'Cifrão' },
  { key: 'ShoppingCart', label: 'Carrinho de compras' },
  { key: 'Shirt', label: 'Roupas' },
  { key: 'Gamepad2', label: 'Jogos' },
  { key: 'Car', label: 'Carro' },
  { key: 'Home', label: 'Casa' },
  { key: 'Receipt', label: 'Recibo' },
  { key: 'CreditCard', label: 'Cartão de crédito' },
  { key: 'Shield', label: 'Seguro' },
  { key: 'Plane', label: 'Viagem aérea' },
  { key: 'PiggyBank', label: 'Cofrinho' },
  { key: 'Landmark', label: 'Banco' },
  { key: 'TrendingUp', label: 'Crescimento' },
  { key: 'Utensils', label: 'Alimentação' },
  { key: 'Heart', label: 'Bem-estar' },
  { key: 'Zap', label: 'Energia elétrica' },
  { key: 'Wifi', label: 'Internet' },
  { key: 'Smartphone', label: 'Celular' },
  { key: 'Book', label: 'Livros' },
  { key: 'GraduationCap', label: 'Educação' },
  { key: 'Stethoscope', label: 'Saúde' },
  { key: 'Baby', label: 'Bebê' },
  { key: 'Gift', label: 'Presente' },
  { key: 'Bus', label: 'Ônibus' },
  { key: 'Fuel', label: 'Combustível' },
  { key: 'Video', label: 'Vídeo' },
  { key: 'Banknote', label: 'Dinheiro em espécie' },
  { key: 'Building2', label: 'Empresa' },
  { key: 'Droplet', label: 'Água' },
  { key: 'Flame', label: 'Gás' },
] as const

export const CATEGORY_ICONS = CATEGORY_ICON_OPTIONS.map((o) => o.key)

interface CategoryIconProps {
  icon: string
  className?: string
  size?: number
}

export function CategoryIcon({ icon, className, size = 20 }: CategoryIconProps) {
  const IconComponent = iconMap[icon] ?? CircleDollarSign
  return <IconComponent className={cn('shrink-0', className)} size={size} />
}
