import {
  Wallet,
  Coins,
  Laptop,
  CircleDollarSign,
  ShoppingCart,
  Shirt,
  Gamepad2,
  Car,
  Home,
  Receipt,
  CreditCard,
  Shield,
  Plane,
  PiggyBank,
  Landmark,
  TrendingUp,
  Utensils,
  Heart,
  Zap,
  Wifi,
  Smartphone,
  Book,
  GraduationCap,
  Stethoscope,
  Baby,
  Gift,
  Bus,
  Fuel,
  LucideIcon,
  Video,
  Banknote,
  Building2,
  Droplet,
  Flame,
  Music,
} from 'lucide-react'
import { cn } from '@/lib/utils'

const iconMap: Record<string, LucideIcon> = {
  Wallet,
  Coins,
  Laptop,
  CircleDollarSign,
  ShoppingCart,
  Shirt,
  Gamepad2,
  Car,
  Home,
  Receipt,
  CreditCard,
  Shield,
  Plane,
  PiggyBank,
  Landmark,
  TrendingUp,
  Utensils,
  Heart,
  Zap,
  Wifi,
  Smartphone,
  Book,
  GraduationCap,
  Stethoscope,
  Baby,
  Gift,
  Bus,
  Fuel,
  Video,
  Banknote,
  Building2,
  Droplet,
  Flame,
  Music,
}

/** Lucide icon keys available for categories (labels via `common.icons`). */
export const CATEGORY_ICON_OPTIONS = [
  'Wallet',
  'Coins',
  'Laptop',
  'CircleDollarSign',
  'ShoppingCart',
  'Shirt',
  'Gamepad2',
  'Car',
  'Home',
  'Receipt',
  'CreditCard',
  'Shield',
  'Plane',
  'PiggyBank',
  'Landmark',
  'TrendingUp',
  'Utensils',
  'Heart',
  'Zap',
  'Wifi',
  'Smartphone',
  'Book',
  'GraduationCap',
  'Stethoscope',
  'Baby',
  'Gift',
  'Bus',
  'Fuel',
  'Video',
  'Banknote',
  'Building2',
  'Droplet',
  'Flame',
  'Music',
] as const

export const CATEGORY_ICONS = CATEGORY_ICON_OPTIONS

interface CategoryIconProps {
  icon: string
  className?: string
  size?: number
}

export function CategoryIcon({ icon, className, size = 20 }: CategoryIconProps) {
  const IconComponent = iconMap[icon] ?? CircleDollarSign
  return <IconComponent className={cn('shrink-0', className)} size={size} />
}
