export const DEFAULT_CATEGORIES = {
  income: [
    { group: 'Receitas', name: 'Salário', icon: 'Wallet', color: '#22c55e' },
    { group: 'Receitas', name: 'Bônus e comissões', icon: 'Coins', color: '#eab308' },
    { group: 'Receitas', name: 'Freelance', icon: 'Laptop', color: '#3b82f6' },
    { group: 'Receitas', name: 'Rendimentos', icon: 'TrendingUp', color: '#06b6d4' },
    { group: 'Receitas', name: 'Aluguel recebido', icon: 'Home', color: '#8b5cf6' },
    { group: 'Receitas', name: 'Venda de ativos', icon: 'Banknote', color: '#f97316' },
    { group: 'Receitas', name: 'Outros', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
  expense: [
    { group: 'Moradia', name: 'Aluguel ou hipoteca', icon: 'Home', color: '#8b5cf6', isFixed: true },
    { group: 'Moradia', name: 'Condomínio', icon: 'Building2', color: '#a855f7', isFixed: true },
    { group: 'Moradia', name: 'IPTU', icon: 'Receipt', color: '#64748b', isFixed: true },
    { group: 'Moradia', name: 'Conta de água', icon: 'Droplet', color: '#2563eb', isFixed: true },
    { group: 'Moradia', name: 'Conta de luz', icon: 'Zap', color: '#facc15', isFixed: true },
    { group: 'Moradia', name: 'Conta de gás', icon: 'Flame', color: '#f59e0b', isFixed: true },
    { group: 'Moradia', name: 'Manutenção da casa', icon: 'Landmark', color: '#475569', isFixed: false },
    { group: 'Alimentação', name: 'Supermercado', icon: 'ShoppingCart', color: '#22c55e', isFixed: false },
    { group: 'Alimentação', name: 'Feira/Hortifruti', icon: 'ShoppingCart', color: '#16a34a', isFixed: false },
    { group: 'Alimentação', name: 'Açougue', icon: 'Utensils', color: '#15803d', isFixed: false },
    { group: 'Alimentação', name: 'Padaria', icon: 'Utensils', color: '#ca8a04', isFixed: false },
    { group: 'Alimentação', name: 'Restaurantes', icon: 'Utensils', color: '#f97316', isFixed: false },
    { group: 'Alimentação', name: 'Delivery', icon: 'Utensils', color: '#ea580c', isFixed: false },
    { group: 'Alimentação', name: 'Lanches e Fast Food', icon: 'Utensils', color: '#fb923c', isFixed: false },
    { group: 'Alimentação', name: 'Cafeterias e Sobremesas', icon: 'Utensils', color: '#d97706', isFixed: false },
    { group: 'Alimentação', name: 'Almoço Trabalho', icon: 'Utensils', color: '#b45309', isFixed: false },
    { group: 'Alimentação', name: 'Bebidas Alcoólicas', icon: 'Utensils', color: '#991b1b', isFixed: false },
    { group: 'Alimentação', name: 'Suplementos', icon: 'Heart', color: '#059669', isFixed: false },
    { group: 'Transporte', name: 'Combustível', icon: 'Car', color: '#06b6d4', isFixed: false },
    { group: 'Transporte', name: 'Transporte público', icon: 'Bus', color: '#0ea5e9', isFixed: false },
    { group: 'Transporte', name: 'Seguro do carro', icon: 'Shield', color: '#14b8a6', isFixed: true },
    { group: 'Transporte', name: 'Uber e 99', icon: 'Car', color: '#1e293b', isFixed: false },
    { group: 'Transporte', name: 'Manutenção do carro', icon: 'Car', color: '#334155', isFixed: false },
    { group: 'Saúde', name: 'Plano de saúde', icon: 'Shield', color: '#14b8a6', isFixed: true },
    { group: 'Saúde', name: 'Farmácia', icon: 'Heart', color: '#e11d48', isFixed: false },
    { group: 'Saúde', name: 'Consultas e exames', icon: 'Stethoscope', color: '#0d9488', isFixed: false },
    { group: 'Saúde', name: 'Academia', icon: 'Heart', color: '#16a34a', isFixed: true },
    { group: 'Educação', name: 'Mensalidade escolar', icon: 'BookOpen', color: '#3b82f6', isFixed: true },
    { group: 'Educação', name: 'Cursos', icon: 'GraduationCap', color: '#2563eb', isFixed: false },
    { group: 'Educação', name: 'Materiais', icon: 'Book', color: '#1d4ed8', isFixed: false },
    { group: 'Assinaturas', name: 'Streaming de vídeo', icon: 'Video', color: '#7c3aed', isFixed: true },
    { group: 'Assinaturas', name: 'Streaming de áudio', icon: 'Music', color: '#8b5cf6', isFixed: true },
    { group: 'Assinaturas', name: 'Jogos', icon: 'Gamepad2', color: '#9333ea', isFixed: true },
    { group: 'Assinaturas', name: 'Leitura digital', icon: 'Book', color: '#6d28d9', isFixed: true },
    { group: 'Assinaturas', name: 'Armazenamento', icon: 'Laptop', color: '#5b21b6', isFixed: true },
    { group: 'Assinaturas', name: 'Software e apps', icon: 'Laptop', color: '#4c1d95', isFixed: true },
    { group: 'Assinaturas', name: 'Educação', icon: 'GraduationCap', color: '#3b82f6', isFixed: true },
    { group: 'Lazer e estilo de vida', name: 'Passagem aérea', icon: 'Plane', color: '#0ea5e9', isFixed: false },
    { group: 'Lazer e estilo de vida', name: 'Cinema e eventos', icon: 'Video', color: '#db2777', isFixed: false },
    { group: 'Lazer e estilo de vida', name: 'Hobbies e jogos', icon: 'Gamepad2', color: '#c026d3', isFixed: false },
    { group: 'Pessoal e serviços', name: 'Vestuário', icon: 'Shirt', color: '#ec4899', isFixed: false },
    { group: 'Pessoal e serviços', name: 'Salão e beleza', icon: 'Gift', color: '#f43f5e', isFixed: false },
    { group: 'Pessoal e serviços', name: 'Telefonia e internet', icon: 'Wifi', color: '#5b21b6', isFixed: true },
    { group: 'Dívidas e obrigacões', name: 'Empréstimos', icon: 'Landmark', color: '#475569', isFixed: true },
    { group: 'Dívidas e obrigacões', name: 'Fatura cartão de crédito', icon: 'CreditCard', color: '#6366f1', isFixed: true },
    { group: 'Dívidas e obrigacões', name: 'Impostos e taxas', icon: 'Receipt', color: '#64748b', isFixed: true },
    { group: 'Outros', name: 'Outros gastos', icon: 'CircleDollarSign', color: '#6366f1', isFixed: false },
  ],
  investment_reserve: [
    { group: 'Investimentos', name: 'Reserva de emergência', icon: 'Shield', color: '#22c55e' },
    { group: 'Investimentos', name: 'Reserva viagem', icon: 'Plane', color: '#3b82f6' },
    { group: 'Investimentos', name: 'Reserva longo prazo', icon: 'TrendingUp', color: '#8b5cf6' },
    { group: 'Investimentos', name: 'Reserva aposentadoria', icon: 'PiggyBank', color: '#a855f7' },
    { group: 'Investimentos', name: 'Compra de alto valor', icon: 'Gift', color: '#ec4899' },
    { group: 'Investimentos', name: 'Outros (reserva)', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
  investment_wallet: [
    { group: 'Investimentos', name: 'CDB', icon: 'PiggyBank', color: '#eab308' },
    { group: 'Investimentos', name: 'Poupança', icon: 'Wallet', color: '#22c55e' },
    { group: 'Investimentos', name: 'Tesouro direto', icon: 'Landmark', color: '#8b5cf6' },
    { group: 'Investimentos', name: 'Ações', icon: 'TrendingUp', color: '#06b6d4' },
    { group: 'Investimentos', name: 'FIIs', icon: 'Building2', color: '#0ea5e9' },
    { group: 'Investimentos', name: 'Previdência', icon: 'Shield', color: '#14b8a6' },
    { group: 'Investimentos', name: 'Criptoativos', icon: 'Coins', color: '#f59e0b' },
    { group: 'Investimentos', name: 'Outros (carteira)', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
  /** @deprecated Use investment_reserve and investment_wallet. Kept for backward compat. */
  investment: [
    { group: 'Investimentos', name: 'Reserva de emergência', icon: 'Shield', color: '#22c55e' },
    { group: 'Investimentos', name: 'Reserva viagem', icon: 'Plane', color: '#3b82f6' },
    { group: 'Investimentos', name: 'CDB', icon: 'PiggyBank', color: '#eab308' },
    { group: 'Investimentos', name: 'Tesouro direto', icon: 'Landmark', color: '#8b5cf6' },
    { group: 'Investimentos', name: 'Ações', icon: 'TrendingUp', color: '#06b6d4' },
    { group: 'Investimentos', name: 'Outros', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
} as const
