export const DEFAULT_CATEGORIES = {
  income: [
    { group: 'Receitas', name: 'Salario', icon: 'Wallet', color: '#22c55e' },
    { group: 'Receitas', name: 'Bonus e comissoes', icon: 'Coins', color: '#eab308' },
    { group: 'Receitas', name: 'Freelance', icon: 'Laptop', color: '#3b82f6' },
    { group: 'Receitas', name: 'Rendimentos', icon: 'TrendingUp', color: '#06b6d4' },
    { group: 'Receitas', name: 'Aluguel recebido', icon: 'Home', color: '#8b5cf6' },
    { group: 'Receitas', name: 'Venda de ativos', icon: 'Banknote', color: '#f97316' },
    { group: 'Receitas', name: 'Outros', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
  expense: [
    { group: 'Moradia', name: 'Aluguel ou hipoteca', icon: 'Home', color: '#8b5cf6', isFixed: true },
    { group: 'Moradia', name: 'Condominio', icon: 'Building2', color: '#a855f7', isFixed: true },
    { group: 'Moradia', name: 'IPTU', icon: 'Receipt', color: '#64748b', isFixed: true },
    { group: 'Moradia', name: 'Conta de agua', icon: 'Droplet', color: '#2563eb', isFixed: true },
    { group: 'Moradia', name: 'Conta de luz', icon: 'Zap', color: '#facc15', isFixed: true },
    { group: 'Moradia', name: 'Conta de gas', icon: 'Flame', color: '#f59e0b', isFixed: true },
    { group: 'Moradia', name: 'Manutencao da casa', icon: 'Landmark', color: '#475569', isFixed: false },
    { group: 'Alimentacao', name: 'Supermercado', icon: 'ShoppingCart', color: '#22c55e', isFixed: false },
    { group: 'Alimentacao', name: 'Feira', icon: 'ShoppingCart', color: '#16a34a', isFixed: false },
    { group: 'Alimentacao', name: 'Padaria', icon: 'Utensils', color: '#ca8a04', isFixed: false },
    { group: 'Alimentacao', name: 'Restaurantes', icon: 'Utensils', color: '#f97316', isFixed: false },
    { group: 'Alimentacao', name: 'Delivery', icon: 'Utensils', color: '#ea580c', isFixed: false },
    { group: 'Transporte', name: 'Combustivel', icon: 'Car', color: '#06b6d4', isFixed: false },
    { group: 'Transporte', name: 'Transporte publico', icon: 'Bus', color: '#0ea5e9', isFixed: false },
    { group: 'Transporte', name: 'Seguro do carro', icon: 'Shield', color: '#14b8a6', isFixed: true },
    { group: 'Transporte', name: 'Uber e 99', icon: 'Car', color: '#1e293b', isFixed: false },
    { group: 'Transporte', name: 'Manutencao do carro', icon: 'Car', color: '#334155', isFixed: false },
    { group: 'Saude', name: 'Plano de saude', icon: 'Shield', color: '#14b8a6', isFixed: true },
    { group: 'Saude', name: 'Farmacia', icon: 'Heart', color: '#e11d48', isFixed: false },
    { group: 'Saude', name: 'Consultas e exames', icon: 'Stethoscope', color: '#0d9488', isFixed: false },
    { group: 'Saude', name: 'Academia', icon: 'Heart', color: '#16a34a', isFixed: true },
    { group: 'Educacao', name: 'Mensalidade escolar', icon: 'BookOpen', color: '#3b82f6', isFixed: true },
    { group: 'Educacao', name: 'Cursos', icon: 'GraduationCap', color: '#2563eb', isFixed: false },
    { group: 'Educacao', name: 'Materiais', icon: 'Book', color: '#1d4ed8', isFixed: false },
    { group: 'Lazer e estilo de vida', name: 'Cinema e eventos', icon: 'Video', color: '#db2777', isFixed: false },
    { group: 'Lazer e estilo de vida', name: 'Hobbies e games', icon: 'Gamepad2', color: '#c026d3', isFixed: false },
    { group: 'Lazer e estilo de vida', name: 'Streaming', icon: 'Video', color: '#7c3aed', isFixed: true },
    { group: 'Pessoal e servicos', name: 'Vestuario', icon: 'Shirt', color: '#ec4899', isFixed: false },
    { group: 'Pessoal e servicos', name: 'Salao e beleza', icon: 'Gift', color: '#f43f5e', isFixed: false },
    { group: 'Pessoal e servicos', name: 'Telefonia e internet', icon: 'Wifi', color: '#5b21b6', isFixed: true },
    { group: 'Dividas e obrigacoes', name: 'Emprestimos', icon: 'Landmark', color: '#475569', isFixed: true },
    { group: 'Dividas e obrigacoes', name: 'Fatura cartao de credito', icon: 'CreditCard', color: '#6366f1', isFixed: true },
    { group: 'Dividas e obrigacoes', name: 'Impostos e taxas', icon: 'Receipt', color: '#64748b', isFixed: true },
    { group: 'Outros', name: 'Outros gastos', icon: 'CircleDollarSign', color: '#6366f1', isFixed: false },
  ],
  investment_reserve: [
    { group: 'Investimentos', name: 'Reserva de emergencia', icon: 'Shield', color: '#22c55e' },
    { group: 'Investimentos', name: 'Reserva viagem', icon: 'Plane', color: '#3b82f6' },
    { group: 'Investimentos', name: 'Reserva longo prazo', icon: 'TrendingUp', color: '#8b5cf6' },
    { group: 'Investimentos', name: 'Reserva aposentadoria', icon: 'PiggyBank', color: '#a855f7' },
    { group: 'Investimentos', name: 'Compra de alto valor', icon: 'Gift', color: '#ec4899' },
    { group: 'Investimentos', name: 'Outros (reserva)', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
  investment_wallet: [
    { group: 'Investimentos', name: 'CDB', icon: 'PiggyBank', color: '#eab308' },
    { group: 'Investimentos', name: 'Poupanca', icon: 'Wallet', color: '#22c55e' },
    { group: 'Investimentos', name: 'Tesouro direto', icon: 'Landmark', color: '#8b5cf6' },
    { group: 'Investimentos', name: 'Acoes', icon: 'TrendingUp', color: '#06b6d4' },
    { group: 'Investimentos', name: 'FIIs', icon: 'Building2', color: '#0ea5e9' },
    { group: 'Investimentos', name: 'Previdencia', icon: 'Shield', color: '#14b8a6' },
    { group: 'Investimentos', name: 'Criptoativos', icon: 'Coins', color: '#f59e0b' },
    { group: 'Investimentos', name: 'Outros (carteira)', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
  /** @deprecated Use investment_reserve and investment_wallet. Kept for backward compat. */
  investment: [
    { group: 'Investimentos', name: 'Reserva de emergencia', icon: 'Shield', color: '#22c55e' },
    { group: 'Investimentos', name: 'Reserva viagem', icon: 'Plane', color: '#3b82f6' },
    { group: 'Investimentos', name: 'CDB', icon: 'PiggyBank', color: '#eab308' },
    { group: 'Investimentos', name: 'Tesouro direto', icon: 'Landmark', color: '#8b5cf6' },
    { group: 'Investimentos', name: 'Acoes', icon: 'TrendingUp', color: '#06b6d4' },
    { group: 'Investimentos', name: 'Outros', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
} as const
