export const DEFAULT_CATEGORIES = {
  income: [
    { name: 'Salário', icon: 'Wallet', color: '#22c55e' },
    { name: 'Extra', icon: 'Coins', color: '#eab308' },
    { name: 'Freelance', icon: 'Laptop', color: '#3b82f6' },
    { name: 'Outros', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
  expense: [
    { name: 'Mercado', icon: 'ShoppingCart', color: '#22c55e', isFixed: false },
    { name: 'Roupas', icon: 'Shirt', color: '#ec4899', isFixed: false },
    { name: 'Lazer', icon: 'Gamepad2', color: '#f97316', isFixed: false },
    { name: 'Carro', icon: 'Car', color: '#06b6d4', isFixed: false },
    { name: 'Cartão de crédito', icon: 'CreditCard', color: '#6366f1', isFixed: false },
    { name: 'Aluguel', icon: 'Home', color: '#8b5cf6', isFixed: true },
    { name: 'Contas', icon: 'Receipt', color: '#64748b', isFixed: true },
    { name: 'Pagamentos', icon: 'Banknote', color: '#0ea5e9', isFixed: false },
    { name: 'Farmácia', icon: 'Heart', color: '#e11d48', isFixed: false },
    { name: 'Convênio', icon: 'Shield', color: '#14b8a6', isFixed: true },
    { name: 'Dentista', icon: 'Stethoscope', color: '#0d9488', isFixed: false },
    { name: 'Uber', icon: 'Bus', color: '#1e293b', isFixed: false },
    { name: 'Ifood', icon: 'Utensils', color: '#ea580c', isFixed: false },
    { name: 'Internet móvel', icon: 'Smartphone', color: '#7c3aed', isFixed: true },
    { name: 'Internet residencial', icon: 'Wifi', color: '#5b21b6', isFixed: true },
    { name: 'Energia', icon: 'Zap', color: '#facc15', isFixed: true },
    { name: 'Financiamento', icon: 'Landmark', color: '#475569', isFixed: true },
    { name: 'Condomínio', icon: 'Building2', color: '#a855f7', isFixed: true },
    { name: 'Games', icon: 'Gamepad2', color: '#db2777', isFixed: false },
    { name: 'Água', icon: 'Droplet', color: '#2563eb', isFixed: true },
    { name: 'Gás', icon: 'Flame', color: '#f59e0b', isFixed: true },
    { name: 'Outros', icon: 'CreditCard', color: '#6366f1', isFixed: false },
  ],
  investment_reserve: [
    { name: 'Reserva Emergência', icon: 'Shield', color: '#22c55e' },
    { name: 'Reserva Viagem', icon: 'Plane', color: '#3b82f6' },
    { name: 'Reserva Longo Prazo', icon: 'TrendingUp', color: '#8b5cf6' },
    { name: 'Compra Alto Valor', icon: 'Gift', color: '#ec4899' },
    { name: 'Outros (Reserva)', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
  investment_wallet: [
    { name: 'CDB', icon: 'PiggyBank', color: '#eab308' },
    { name: 'Poupança', icon: 'Wallet', color: '#22c55e' },
    { name: 'Tesouro Direto', icon: 'Landmark', color: '#8b5cf6' },
    { name: 'Ações', icon: 'TrendingUp', color: '#06b6d4' },
    { name: 'Outros (Carteira)', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
  /** @deprecated Use investment_reserve and investment_wallet. Kept for backward compat. */
  investment: [
    { name: 'Reserva Emergência', icon: 'Shield', color: '#22c55e' },
    { name: 'Reserva Viagem', icon: 'Plane', color: '#3b82f6' },
    { name: 'CDB', icon: 'PiggyBank', color: '#eab308' },
    { name: 'Tesouro Direto', icon: 'Landmark', color: '#8b5cf6' },
    { name: 'Ações', icon: 'TrendingUp', color: '#06b6d4' },
    { name: 'Outros', icon: 'CircleDollarSign', color: '#6366f1' },
  ],
} as const
