export default {
  "0": "0",
  "1234": "1234",
  "": "",
  "(11) 99999-9999": "(11) 99999-9999",
  "+1 USA / Canada": "+1 Stati Uniti/Canada",
  "+34 Spain": "+34 Spagna",
  "+351 Portugal": "+351 Portogallo",
  "+44 United Kingdom": "+44 Regno Unito",
  "+55 Brazil": "+55 Brasile",
  "/month": "/month",
  "0.00": "0.00",
  "000.000.000-00": "000.000.000-00",
  "1 day": "1 giorno",
  "1 hour": "1 ora",
  "1 minute": "1 minuto",
  "100%": "100%",
  "2 free months included": "2 mesi gratuiti inclusi",
  "2 months": "2 mesi",
  "2 months free": "2 mesi gratuiti",
  "2 months free — start today": "2 mesi gratuiti: inizia oggi",
  "A reserve with this name already exists": "Esiste già una riserva con questo nome",
  "Account": "Account",
  "Accumulated amount (R$)": "Importo accumulato (R$)",
  "Accumulated amount cannot be negative": "L'importo accumulato non può essere negativo",
  "Accumulated amount updated.": "Importo accumulato aggiornato.",
  "Accumulated:": "Accumulato:",
  "Achieved": "Raggiunto",
  "Actions": "Azioni",
  "Activate subscription": "Attiva l'abbonamento",
  "Activate your subscription": "Attiva il tuo abbonamento",
  "Active": "Attivo",
  "Activity": "Attività",
  "Add": "Aggiungi",
  "Add bill": "Aggiungi fattura",
  "Add contribution": "Aggiungi versamento",
  "Add expense": "Aggiungi spesa",
  "Add expense categories in Settings before adding bills here.": "Aggiungi categorie di spesa in Impostazioni prima di aggiungere le fatture qui.",
  "Add expenses to see the chart": "Aggiungi le spese per vedere il grafico",
  "Add income": "Aggiungi entrata",
  "Add investments to see the chart": "Aggiungi investimenti per visualizzare il grafico",
  "Add recurrence": "Aggiungi ricorrenza",
  "Add transactions to see the chart": "Aggiungi transazioni per vedere il grafico",
  "Add your income this month to compare with recurring bills and get a financial health reading.": "Aggiungi le tue entrate di questo mese per confrontarle con le bollette ricorrenti e ottenere un quadro della tua salute finanziaria.",
  "After the first 2 free months.": "Dopo i primi 2 mesi gratuiti.",
  "After the first 2 months. No charge during the trial period.": "Dopo i primi 2 mesi. Nessun addebito durante il periodo di prova.",
  "After the trial, only R$10/month. No surprises.": "Dopo la prova, solo R$10/month. Nessuna sorpresa.",
  "After the trial, your subscription is automatically charged to the card on file at R$10/month. You will receive a reminder email before the trial ends.": "Dopo il periodo di prova, l'abbonamento verrà automaticamente addebitato sulla carta registrata presso R$10/month. Riceverai un'e-mail di promemoria prima della fine del periodo di prova.",
  "Air travel": "Viaggi aerei",
  "Alcoholic beverages": "Bevande alcoliche",
  "Alert: Overdue bill is shown when due date passes with an open balance.": "Avviso: la fattura scaduta viene visualizzata quando la data di scadenza supera con un saldo aperto.",
  "All": "Tutto",
  "All main categories": "Tutte le categorie principali",
  "Already have an account?": "Hai già un account?",
  "Amount (R$)": "Importo (R$)",
  "Amount (monthly)": "Importo (mensile)",
  "Amount must be greater than or equal to zero": "L'importo deve essere maggiore o uguale a zero",
  "Amount must be positive": "L'importo deve essere positivo",
  "Analysis": "Analisi",
  "Analysis and reports": "Analisi e report",
  "Analyze daily, monthly, and yearly data in one view": "Analizza i dati giornalieri, mensili e annuali in un'unica visualizzazione",
  "Annual": "Annuale",
  "Annual Table": "Tabella annuale",
  "Annual expense table": "Tabella delle spese annuali",
  "Appearance": "Aspetto",
  "Applied": "Applicato",
  "Apply to month": "Applica al mese",
  "Apr": "Apr",
  "April": "Aprile",
  "Are my financial data secure?": "I miei dati finanziari sono al sicuro?",
  "Asset sale": "Vendita di beni",
  "Audio streaming": "Streaming audio",
  "Aug": "Ago",
  "August": "Agosto",
  "Automatic entry": "Inserimento automatico",
  "Automatic insights": "Approfondimenti automatici",
  "Automatic recurring payments": "Pagamenti ricorrenti automatici",
  "Avail.": "Disp.",
  "Available balance:": "Saldo disponibile:",
  "Available cash": "Liquidità disponibile",
  "Available limit (cards)": "Limite disponibile (carte)",
  "Available on larger devices only": "Disponibile solo su dispositivi più grandi",
  "Baby": "Bambino",
  "Back to": "Torna a",
  "Back to login": "Torna al login",
  "Bakery": "Panetteria",
  "Bank": "Banca",
  "Bar chart: expenses by category": "Grafico a barre: spese per categoria",
  "Bill payment (cash) — {cardName}": "Pagamento delle fatture (contanti) — {cardName}",
  "Bill payment:": "Pagamento della fattura:",
  "Bill: Paying on the card tab records a cash expense and restores the limit.": "Fattura: Il pagamento sulla scheda della carta registra una spesa in contanti e ripristina il limite.",
  "Billing portal": "Portale di fatturazione",
  "Bonuses and commissions": "Bonus e commissioni",
  "Books": "Libri",
  "Built for people who want real visibility into their money without unnecessary complexity.": "Progettato per le persone che desiderano una visibilità reale sui propri soldi senza inutili complessità.",
  "Bus": "Autobus",
  "Butcher": "Macelleria",
  "CDB": "CDB",
  "CPF": "CPF",
  "CPF is required": "È richiesto il CPF",
  "CPF must have 11 digits": "CPF deve avere 11 cifre",
  "Cafes and desserts": "Caffè e dessert",
  "Calculated amount for this month is zero.": "L'importo calcolato per questo mese è zero.",
  "Calculation type": "Tipo di calcolo",
  "Can I cancel anytime?": "Posso annullare in qualsiasi momento?",
  "Can't find the reserve? Create a new one without leaving this screen.": "Non trovi la riserva? Creane una nuova senza uscire da questa schermata.",
  "Cancel": "Annulla",
  "Cancel anytime": "Annulla in qualsiasi momento",
  "Cancel anytime · No commitment": "Annulla in qualsiasi momento · Nessun impegno",
  "Cancel anytime · No commitment · No setup fee": "Annulla in qualsiasi momento · Nessun impegno · Nessun costo di installazione",
  "Canceled": "Annullato",
  "Car": "Auto",
  "Car insurance": "Assicurazione auto",
  "Car maintenance": "Manutenzione dell'auto",
  "Card not found": "Carta non trovata",
  "Card purchases reduce the available limit and do not affect cash budget until you pay the bill on the card tab.": "Gli acquisti con carta riducono il limite disponibile e non influiscono sul budget in contanti finché non si paga il conto sulla scheda della carta.",
  "Card purchases this month (outside cash budget until you pay the bill)": "Acquisti con carta questo mese (fuori dal budget in contanti fino al pagamento della fattura)",
  "Card spending": "Spesa con carta",
  "Card spending by main category": "Spesa con carta per categoria principale",
  "Card:": "Carta:",
  "Cards and payments": "Carte e pagamenti",
  "Cash": "Contanti",
  "Cash (cash/PIX)": "Contanti (contanti/PIX)",
  "Cash balance": "Saldo di cassa",
  "Cash flow": "Flusso di cassa",
  "Categories": "Categorie",
  "Categories for expenses that vary month to month": "Categorie per le spese che variano di mese in mese",
  "Categories for recurring and predictable expenses": "Categorie per spese ricorrenti e prevedibili",
  "Categories organize your income, expenses, and spending. You can have fixed expenses (rent, bills) and variable ones (groceries, leisure). Create and edit them in Settings as needed.": "Le categorie organizzano entrate, uscite e spese. Puoi avere spese fisse (affitto, bollette) e variabili (generi alimentari, tempo libero). Creali e modificali in Impostazioni secondo necessità.",
  "Categories to record your income": "Categorie per registrare le tue entrate",
  "Category": "Categoria",
  "Category not found": "Categoria non trovata",
  "Centralized income and expenses": "Entrate e spese centralizzate",
  "Change password": "Cambia password",
  "Change the day in the calendar on the left to record on this date.": "Cambia il giorno nel calendario a sinistra per registrare in questa data.",
  "Changing...": "Modifica in corso...",
  "Choose a new password for your account": "Scegli una nuova password per il tuo account",
  "Choose the interface language": "Scegli la lingua dell'interfaccia",
  "Choose whether the contribution should use monthly cash or only be tracked.": "Scegli se il contributo dovrà essere in contanti mensile o solo tracciabile.",
  "Cinema and events": "Cinema ed eventi",
  "Clear filters": "Cancella filtri",
  "Close": "Chiudi",
  "Close navigation menu": "Chiudi il menu di navigazione",
  "Closing and due dates are reference in setup; overdue with open balance may trigger an alert": "Le date di chiusura e scadenza sono riferimento nella configurazione; scaduto con saldo aperto può attivare un avviso",
  "Closing day": "Giorno di chiusura",
  "Clothing": "Vestiario",
  "Coins": "Monete",
  "Collapse sidebar": "Comprimi la barra laterale",
  "Color": "Colore",
  "Color is required": "Il colore è obbligatorio",
  "Company": "Azienda",
  "Comparison with previous month": "Confronto con il mese precedente",
  "Condo fee": "Spese condominiali",
  "Confirm": "Conferma",
  "Confirm new password": "Conferma la nuova password",
  "Confirm password": "Conferma password",
  "Confirm payment": "Conferma il pagamento",
  "Consolidated investments": "Investimenti consolidati",
  "Consolidated net worth": "Patrimonio netto consolidato",
  "Continue": "Continua",
  "Continuing...": "Continuo...",
  "Contributions": "Contributi",
  "Could not confirm subscription automatically. Configure the Stripe webhook or try opening the customer portal in settings.": "Impossibile confermare automaticamente l'abbonamento. Configura il webhook Stripe o prova ad aprire il portale clienti nelle Impostazioni.",
  "Could not register the month for this item.": "Impossibile registrare il mese per questo articolo.",
  "Could not register the month.": "Impossibile registrare il mese.",
  "Country code": "Codice paese",
  "Country code is required": "Il codice paese è obbligatorio",
  "Courses": "Corsi",
  "Create a variable expense category in Settings": "Crea una categoria di spesa variabile in Impostazioni",
  "Create account": "Crea account",
  "Create free account": "Crea un account gratuito",
  "Create goal": "Crea obiettivo",
  "Create new goal": "Crea un nuovo obiettivo",
  "Create reserve": "Crea riserva",
  "Creating...": "Creazione...",
  "Credit Card": "Carta di credito",
  "Credit card": "Carta di credito",
  "Credit card bill": "Fattura della carta di credito",
  "Credit card control": "Controllo della carta di credito",
  "Credit card management": "Gestione carte di credito",
  "Crypto assets": "Criptovalute",
  "Current password": "Password attuale",
  "Current password is required": "È richiesta la password attuale",
  "Custom": "Personalizzato",
  "Custom categories": "Categorie personalizzate",
  "Daily": "Giornaliero",
  "Dark mode in one click": "Modalità scura in un clic",
  "Date": "Data",
  "Date is required": "La data è obbligatoria",
  "Day": "Giorno",
  "Day {day}, {entryLabel}": "Giorno {day}, {entryLabel}",
  "Deadline": "Scadenza",
  "Deadline passed. {amount} remaining to complete.": "La scadenza è passata. {amount} rimanenti da completare.",
  "Deadline:": "Scadenza:",
  "Debts and obligations": "Debiti e obblighi",
  "Dec": "Dic",
  "December": "Dicembre",
  "Delete": "Elimina",
  "Delete recurring investment": "Elimina l'investimento ricorrente",
  "Delete this card?": "Eliminare questa carta?",
  "Delete this category? Linked transactions and investments will also be removed.": "Eliminare questa categoria? Verranno rimossi anche le transazioni e gli investimenti collegati.",
  "Delete this contribution?": "Eliminare questo contributo?",
  "Delete this recurring bill?": "Eliminare questa fattura ricorrente?",
  "Delete this recurring bill? Monthly occurrences will also be removed.": "Eliminare questa fattura ricorrente? Verranno rimosse anche le occorrenze mensili.",
  "Delete this recurring investment?": "Eliminare questo investimento ricorrente?",
  "Delete this transaction?": "Eliminare questa transazione?",
  "Delete {name}": "Elimina {name}",
  "Delivery": "Consegna",
  "Description": "Descrizione",
  "Digital reading": "Lettura digitale",
  "Dismiss trial ending notice": "Chiudi l'avviso di fine prova",
  "Distribution of card purchases grouped by registered main categories": "Distribuzione degli acquisti con carta raggruppati per categorie principali registrate",
  "Do I need to enter a credit card to start?": "Devo inserire una carta di credito per iniziare?",
  "Do you really want to delete this goal?": "Vuoi davvero eliminare questo obiettivo?",
  "Does it work on mobile devices?": "Funziona sui dispositivi mobili?",
  "Dollar sign": "Segno del dollaro",
  "Don't have an account?": "Non hai un account?",
  "Donut chart: card spending by main category": "Grafico a ciambella: spesa con carta per categoria principale",
  "Donut chart: fixed and variable expenses": "Grafico a ciambella: spese fisse e variabili",
  "Donut chart: income, expenses, and card spending": "Grafico a ciambella: entrate, spese e spesa con la carta",
  "Donut chart: investment distribution by type": "Grafico a ciambella: distribuzione degli investimenti per tipologia",
  "Due": "Scadenza",
  "Due day": "Giorno di scadenza",
  "E.g.: 10": "Esempio: 10",
  "E.g.: Emergency fund": "Es.: Fondo di emergenza",
  "E.g.: Groceries": "Ad esempio: generi alimentari",
  "E.g.: Nubank": "Ad esempio: Nubank",
  "E.g.: Nubank, Chase": "Ad esempio: Nubank, Chase",
  "E.g.: Trip, home, reserve...": "Es.: viaggio, casa, riserva...",
  "E.g.: rent, internet, utilities": "Ad esempio: affitto, internet, utenze",
  "Edit": "Modifica",
  "Edit recurring bill": "Modifica fattura ricorrente",
  "Edit your personal information and change your password": "Modifica le tue informazioni personali e cambia la tua password",
  "Editing month": "Mese di modifica",
  "Education": "Istruzione",
  "Electricity": "Elettricità",
  "Electricity bill": "Bolletta elettrica",
  "Email": "E-mail",
  "Emergency fund": "Fondo di emergenza",
  "Enable dark theme": "Abilita il tema scuro",
  "Enable light theme": "Abilita il tema chiaro",
  "English": "English",
  "Enter a percentage greater than zero": "Inserisci una percentuale maggiore di zero",
  "Enter your email and we will send a link to reset your password": "Inserisci la tua email e ti invieremo un link per reimpostare la tua password",
  "Error starting checkout": "Errore durante l'avvio del pagamento",
  "Everything you need to organize your finances.": "Tutto ciò di cui hai bisogno per organizzare le tue finanze.",
  "Expand sidebar": "Espandi la barra laterale",
  "Expected total this month:": "Totale previsto questo mese:",
  "Expense (Fixed)": "Spese (fisse)",
  "Expense (Variable)": "Spesa (variabile)",
  "Expense details": "Dettagli sulle spese",
  "Expenses": "Spese",
  "Expenses (current month)": "Spese (mese corrente)",
  "Experience anywhere": "Esperienza ovunque",
  "FAQ": "Domande frequenti",
  "Farmers market / produce": "Mercato contadino / ortofrutta",
  "Features": "Funzionalità",
  "Feb": "Feb",
  "February": "Febbraio",
  "Filter by category": "Filtra per categoria",
  "Filter by category, main category, or date": "Filtra per categoria, categoria principale o data",
  "Filter by credit card or balance": "Filtra per carta di credito o saldo",
  "Filter by main category": "Filtra per categoria principale",
  "Filter transactions": "Filtra le transazioni",
  "Final Balance": "Saldo finale",
  "Financial Analysis": "Analisi finanziaria",
  "Financial goals": "Obiettivi finanziari",
  "Financial goals with progress": "Obiettivi finanziari con progressi",
  "First name": "Nome",
  "Fixed": "Fisso",
  "Fixed amount": "Importo fisso",
  "Fixed expenses": "Spese fisse",
  "Fixed monthly amount": "Importo mensile fisso",
  "Fixed vs variable expenses": "Spese fisse vs variabili",
  "Fixed vs variable expenses, comparisons, and indicators": "Spese fisse e variabili, confronti e indicatori",
  "Flights": "Voli",
  "Food": "Cibo",
  "For percentages, the applied amount considers only monthly income.": "Per le percentuali, l'importo applicato considera solo le entrate mensili.",
  "Forgot my password": "Ho dimenticato la password",
  "Free trial ending": "Fine della prova gratuita",
  "Freelance": "Lavoro autonomo",
  "Frequently asked questions.": "Domande frequenti.",
  "Fri": "Ven",
  "Fuel": "Carburante",
  "Full financial dashboard": "Cruscotto finanziario completo",
  "Games": "Giochi",
  "Gas": "Gas",
  "Gas bill": "Bolletta del gas",
  "General": "Generale",
  "Gift": "Regalo",
  "Go to categories": "Vai alle categorie",
  "Goal name": "Nome dell'obiettivo",
  "Goal name is required": "Il nome dell'obiettivo è obbligatorio",
  "Goal not found": "Obiettivo non trovato",
  "Goal progress donut chart": "Grafico ad anello del progresso dell'obiettivo",
  "Goal reached. Congratulations!": "Obiettivo raggiunto. Congratulazioni!",
  "Goal with no deadline. {amount} remaining to complete.": "Obiettivo senza scadenza. Mancano {amount} per completarlo.",
  "Goals": "Obiettivi",
  "Goals linked to a reserve are updated automatically by contributions": "Gli obiettivi collegati ad una riserva vengono aggiornati automaticamente dai contributi",
  "Great job: recurring bills are up to 60% of income. You keep good margin for surprises and goals.": "Ottimo lavoro: le bollette ricorrenti rappresentano fino al 60% delle entrate. Hai un buon margine per imprevisti e obiettivi.",
  "Growth": "Crescita",
  "Gym": "Palestra",
  "Health": "Salute",
  "Health plan": "Piano sanitario",
  "Hello": "Ciao",
  "Hello, {name}": "Ciao, {name}",
  "Here is your overview for the current month.": "Ecco la panoramica per il mese corrente.",
  "High-value purchase": "Acquisto di alto valore",
  "Hobbies and games": "Hobby e giochi",
  "Home": "Home",
  "Home maintenance": "Manutenzione della casa",
  "Housing": "Abitazione",
  "How does credit card control work?": "Come funziona il controllo delle carte di credito?",
  "I already have an account": "Ho già un account",
  "I want to receive emails about Logos Finance news and improvements (optional).": "Desidero ricevere e-mail sulle novità e sui miglioramenti di Logos Finance (facoltativo).",
  "Icon": "Icona",
  "Icon is required": "L'icona è obbligatoria",
  "If an account exists with this email, we sent password reset instructions.": "Se esiste un account con questa email, abbiamo inviato le istruzioni per la reimpostazione della password.",
  "If the button does not work, copy and paste this address into your browser:": "Se il pulsante non funziona, copia e incolla questo indirizzo nel tuo browser:",
  "If there is an entry this month, values will be updated there too.": "Se c'è una voce questo mese, i valori verranno aggiornati anche lì.",
  "If you did not request this, ignore this email.": "Se non lo hai richiesto, ignora questa email.",
  "If you have any questions, we are here to help.": "Se hai domande, siamo qui per aiutarti.",
  "Include area code. For Brazil, use 11 digits (mobile) or 10 (landline).": "Includi prefisso. Per il Brasile, utilizza 11 cifre (mobile) o 10 (rete fissa).",
  "Income": "Entrate",
  "Income (current month)": "Entrate (mese corrente)",
  "Income and expense tracking": "Monitoraggio delle entrate e delle spese",
  "Income options": "Opzioni di entrata",
  "Income vs Expenses": "Entrate vs spese",
  "Incomplete": "Incompleto",
  "Incorrect current password": "Password attuale errata",
  "Insufficient available limit": "Limite disponibile insufficiente",
  "Insufficient balance in selected reserve/wallet combination": "Saldo insufficiente nella combinazione riserva/portafoglio selezionata",
  "Insufficient monthly cash balance (available: R$ {amount})": "Saldo di cassa mensile insufficiente (disponibile: R$ {amount})",
  "Insurance": "Assicurazione",
  "Interface built for clarity.": "Interfaccia costruita per chiarezza.",
  "Internet": "Internet",
  "Invalid CPF": "CPF non valido",
  "Invalid category": "Categoria non valida",
  "Invalid category type": "Tipo di categoria non valido",
  "Invalid credit card": "Carta di credito non valida",
  "Invalid day": "Giorno non valido",
  "Invalid deadline": "Scadenza non valida",
  "Invalid email": "E-mail non valida",
  "Invalid email or password": "E-mail o password non valide",
  "Invalid link": "Collegamento non valido",
  "Invalid or expired link. Request a new password reset email.": "Collegamento non valido o scaduto. Richiedi una nuova email per la reimpostazione della password.",
  "Invalid percentage": "Percentuale non valida",
  "Invalid phone for selected country code": "Telefono non valido per il prefisso internazionale selezionato",
  "Invalid phone: use area code + number (10 or 11 digits)": "Telefono non valido: utilizzare prefisso + numero (10 o 11 cifre)",
  "Invalid recurring payment": "Pagamento ricorrente non valido",
  "Invalid reserve": "Riserva non valida",
  "Invalid token": "Token non valido",
  "Invalid transaction type": "Tipo di transazione non valido",
  "Invalid wallet": "Portafoglio non valido",
  "Investment": "Investimento",
  "Investment Categories": "Categorie di investimento",
  "Investment tracking": "Monitoraggio degli investimenti",
  "Investments": "Investimenti",
  "Item not found": "Articolo non trovato",
  "Jan": "Gen",
  "January": "Gennaio",
  "Jul": "Lug",
  "July": "Luglio",
  "Jun": "Giu",
  "June": "Giugno",
  "Language": "Lingua",
  "Laptop": "Computer portatile",
  "Last 4 digits": "Ultime 4 cifre",
  "Last name": "Cognome",
  "Last name must be at least 2 characters": "Il cognome deve contenere almeno 2 caratteri",
  "Leisure and lifestyle": "Tempo libero e stile di vita",
  "Line chart: monthly trend of income, expenses, and investments": "Grafico a linee: andamento mensile di entrate, spese e investimenti",
  "Linked reserve: {name}": "Riserva collegata: {name}",
  "Loading application...": "Caricamento dell'applicazione...",
  "Loading your financial dashboard...": "Caricamento del dashboard finanziario...",
  "Loading...": "Caricamento...",
  "Loans": "Prestiti",
  "Logos Finance": "Logos Finance",
  "Logos Finance — Personal finance control": "Logos Finance: controllo delle finanze personali",
  "Logos Finance — home": "Logos Finance — home",
  "Long-term fund": "Fondo a lungo termine",
  "Main category": "Categoria principale",
  "Main dashboard demo": "Demo della dashboard principale",
  "Main navigation": "Navigazione principale",
  "Make withdrawal": "Effettua il prelievo",
  "Manage income and expense categories": "Gestisci le categorie di entrate e spese",
  "Manage reserves (goals) and wallets (allocations) for your investments": "Gestisci le riserve (obiettivi) e i portafogli (allocazioni) per i tuoi investimenti",
  "Manage subscription": "Gestisci l'abbonamento",
  "Manage your plan, billing, and access to premium features.": "Gestisci il tuo piano, la fatturazione e l'accesso alle funzionalità premium.",
  "Manage your profile and categories": "Gestisci il tuo profilo e le tue categorie",
  "Mar": "Mar",
  "March": "Marzo",
  "Mark {name} as paid": "Contrassegna {name} come pagato",
  "Mary": "Maria",
  "Materials": "Materiali",
  "Max. payment": "Pagamento max.",
  "Maximum payable: R$ {amount}": "Massimo pagabile: R$ {amount}",
  "May": "Maggio",
  "Medical appointments and exams": "Visite ed esami medici",
  "Menu": "Menu",
  "Minimum 6 characters": "Minimo 6 caratteri",
  "Missing or invalid token.": "Token mancante o non valido.",
  "Mobile phone": "Telefono cellulare",
  "Mon": "Lun",
  "Month": "Mese",
  "Month calendar": "Calendario mensile",
  "Month summary": "Riepilogo del mese",
  "Monthly": "Mensile",
  "Monthly balance": "Saldo mensile",
  "Monthly bills": "Bollette mensili",
  "Monthly reports and analysis": "Rapporti mensili e analisi",
  "Monthly statement": "Estratto conto mensile",
  "Monthly trend (last 6 months)": "Andamento mensile (ultimi 6 mesi)",
  "Monthly trend charts, spending by category, and annual comparisons. See where every dollar goes.": "Grafici di tendenza mensili, spesa per categoria e confronti annuali. Scopri dove va a finire ogni dollaro.",
  "Music": "Musica",
  "My cards": "Le mie carte",
  "Name is required": "Il nome è obbligatorio",
  "Name must be at least 2 characters": "Il nome deve contenere almeno 2 caratteri",
  "New card": "Nuova carta",
  "New category": "Nuova categoria",
  "New expense form": "Nuovo modulo spese",
  "New expense form for the date selected in the calendar": "Nuovo modulo spese per la data selezionata nel calendario",
  "New income form for the date selected in the calendar": "Nuovo modulo di entrata per la data selezionata nel calendario",
  "New password": "Nuova password",
  "New password must be at least 6 characters": "La nuova password deve contenere almeno 6 caratteri",
  "New recurring bill": "Nuova fattura ricorrente",
  "New recurring contribution": "Nuovo contributo ricorrente",
  "Next": "Prossimo",
  "Next month": "Il mese prossimo",
  "Next renewal": "Prossimo rinnovo",
  "No balance available for withdrawal. Make contributions first.": "Nessun saldo disponibile per il prelievo. Effettua prima dei versamenti.",
  "No bill to pay on this card": "Nessuna fattura da pagare su questa carta",
  "No bills found with the applied filters.": "Nessuna fattura trovata con i filtri applicati.",
  "No card required to sign up": "Nessuna carta richiesta per registrarsi",
  "No card spending in this period": "Nessuna spesa con la carta in questo periodo",
  "No card spending this month": "Nessuna spesa con carta questo mese",
  "No cards registered. Add a card to get started.": "Nessuna carta registrata. Aggiungi una carta per iniziare.",
  "No categories registered": "Nessuna categoria registrata",
  "No contributions or withdrawals in this period": "Nessun contributo o prelievo in questo periodo",
  "No data for the period": "Nessun dato per il periodo",
  "No deadline": "Nessuna scadenza",
  "No description": "Nessuna descrizione",
  "No expense categories. Add at least one in Settings to record expenses.": "Nessuna categoria di spesa. Aggiungine almeno una nelle Impostazioni per registrare le spese.",
  "No expenses in this period": "Nessuna spesa in questo periodo",
  "No income categories. Add at least one in Settings to record income.": "Nessuna categoria di entrata. Aggiungine almeno una nelle Impostazioni per registrare le entrate.",
  "No income in this period": "Nessuna entrata in questo periodo",
  "No linked reserve": "Nessuna riserva vincolata",
  "No main category": "Nessuna categoria principale",
  "No previous baseline": "Nessuna base di riferimento precedente",
  "No recent transactions": "Nessuna transazione recente",
  "No recurring bills registered. Use \"Add bill\" to include items that repeat every month.": "Nessuna fattura ricorrente registrata. Utilizza \"Aggiungi fattura\" per includere elementi che si ripetono ogni mese.",
  "No recurring bills this month.": "Nessuna fattura ricorrente questo mese.",
  "No recurring contributions this month.": "Nessun contributo ricorrente questo mese.",
  "No recurring investments registered.": "Nessun investimento ricorrente registrato.",
  "No repetitive work": "Nessun lavoro ripetitivo",
  "No results for the selected filters.": "Nessun risultato per i filtri selezionati.",
  "No results found": "Nessun risultato trovato",
  "No subscription": "Nessun abbonamento",
  "No subscription found. Activate your plan to keep full access.": "Nessun abbonamento trovato. Attiva il tuo piano per mantenere l'accesso completo.",
  "No transactions found in this period.": "Nessuna transazione trovata in questo periodo.",
  "No, track only": "No, solo traccia",
  "Notes": "Note",
  "Nov": "Nov",
  "November": "Novembre",
  "Number with area code": "Numero con prefisso",
  "Oct": "Ott",
  "October": "Ottobre",
  "Open navigation menu": "Apri il menu di navigazione",
  "Open the link sent by email or request a new password reset.": "Apri il collegamento inviato via email o richiedi una nuova reimpostazione della password.",
  "Opening...": "Apertura...",
  "Optional": "Opzionale",
  "Organize income, expenses, credit cards, investments, and goals in a clear, simple dashboard.": "Organizza entrate, spese, carte di credito, investimenti e obiettivi in ​​una dashboard chiara e semplice.",
  "Origin (Reserve → Wallet)": "Origine (Riserva → Portafoglio)",
  "Other": "Altro",
  "Other (reserve)": "Altro (riserva)",
  "Other (wallet)": "Altro (portafoglio)",
  "Other expenses": "Altre spese",
  "Overdue credit card bill": "Fattura della carta di credito scaduta",
  "Overview": "Panoramica",
  "Page {current} of {total}": "Pagina {current} di {total}",
  "Paid": "Pagato",
  "Password": "Password",
  "Password changed successfully": "La password è stata modificata con successo",
  "Password changed successfully. Redirecting to login…": "La password è stata modificata con successo. Reindirizzamento all'accesso...",
  "Password confirmation is required": "È richiesta la conferma della password",
  "Password must be at least 6 characters": "La password deve contenere almeno 6 caratteri",
  "Passwords do not match": "Le password non corrispondono",
  "Past due": "Scaduto",
  "Pay": "Paga",
  "Pay bill": "Paga fattura",
  "Paying...": "Pagamento...",
  "Payment method": "Metodo di pagamento",
  "Payment uses only the <cash>cash balance for the month</cash> (income minus budget expenses and investments), <expense>records an expense</expense> in that month, and <limit>restores the card limit</limit>.": "Il pagamento utilizza solo il <cash>saldo contante per il mese</cash> (entrate meno spese e investimenti di budget), <expense>registra una spesa</expense> in quel mese e <limit>ripristina il limite della carta</limit>.",
  "Payment: Uses cash balance and restores card limit.": "Pagamento: utilizza il saldo in contanti e ripristina il limite della carta.",
  "Payments": "Pagamenti",
  "Pending": "In sospeso",
  "Pension": "Previdenza",
  "Percentage (%)": "Percentuale (%)",
  "Percentage of monthly income": "Percentuale delle entrate mensili",
  "Period total": "Totale periodo",
  "Personal and services": "Personale e servizi",
  "Personal finance dashboard for people who want clarity about their money.": "Dashboard di finanza personale per le persone che desiderano chiarezza sui propri soldi.",
  "Pharmacy": "Farmacia",
  "Phone": "Telefono",
  "Phone and internet": "Telefono e Internet",
  "Phone is required": "È richiesto il telefono",
  "Piggy bank": "Salvadanaio",
  "Plan": "Piano",
  "Please wait...": "Attendi...",
  "Portuguese (Brazil)": "Portoghese (Brasile)",
  "Preset amount (R$)": "Importo preimpostato (R$)",
  "Previous": "Precedente",
  "Previous month": "Mese precedente",
  "Previous month: {amount}": "Mese precedente: {amount}",
  "Price": "Prezzo",
  "Pricing": "Prezzi",
  "Pro Monthly": "Pro Mensile",
  "Processing...": "Elaborazione...",
  "Product": "Prodotto",
  "Profile": "Profilo",
  "Profile updated successfully": "Profilo aggiornato con successo",
  "Progress:": "Progressi:",
  "Property tax": "Imposta sulla proprietà",
  "Public transport": "Trasporto pubblico",
  "Purchases do not affect cash budget; paying the bill records an expense and restores the limit": "Gli acquisti non incidono sul budget di cassa; il pagamento della fattura registra una spesa e ripristina il limite",
  "Purchases: Reduce the limit immediately and do not affect cash budget.": "Acquisti: Riducono immediatamente il limite e non incidono sul budget di cassa.",
  "R$": "R$",
  "R$10": "R$10",
  "R$10.00 / month": "R$10.00 / mese",
  "REITs": "REITs",
  "Ready to organize": "Pronto a organizzare",
  "Real-time limit": "Limite in tempo reale",
  "Receipt": "Ricevuta",
  "Receive emails about product news and improvements": "Ricevi e-mail su novità e miglioramenti sui prodotti",
  "Recent spending": "Spesa recente",
  "Recent transactions": "Transazioni recenti",
  "Record contributions in Investments. Each contribution links a reserve (goal) to a wallet (allocation). Track total invested by category.": "Registra i versamenti in Investimenti. Ogni versamento collega una riserva (obiettivo) a un portafoglio (allocazione). Monitora il totale investito per categoria.",
  "Record contributions to emergency reserves and wallets. Track your net worth growth.": "Registra versamenti in riserve e portafogli. Monitora la crescita del tuo patrimonio netto.",
  "Record income and expenses with category, date, and description. View cash flow month by month without spreadsheets.": "Registra entrate e uscite con categoria, data e descrizione. Visualizza il flusso di cassa mese per mese senza fogli di calcolo.",
  "Recurring": "Ricorrente",
  "Recurring bills represent {ratio}% of monthly income.": "Le bollette ricorrenti rappresentano il {ratio}% delle entrate mensili.",
  "Recurring bills: {recurring} · Monthly income: {income}": "Bollette ricorrenti: {recurring} · Entrate mensili: {income}",
  "Recurring contributions": "Contributi ricorrenti",
  "Recurring investment not found": "Investimento ricorrente non trovato",
  "Recurring investments": "Investimenti ricorrenti",
  "Recurring payment": "Pagamento ricorrente",
  "Recurring payment not found": "Pagamento ricorrente non trovato",
  "Recurring payments": "Pagamenti ricorrenti",
  "Recurring payments and fixed expenses share the same data. Changes here also update your fixed entries.": "I pagamenti ricorrenti e le spese fisse condividono gli stessi dati. Le modifiche qui aggiornano anche le voci fisse.",
  "Redirecting...": "Reindirizzamento...",
  "Register": "Registrati",
  "Register card": "Registra la carta",
  "Register subscriptions and fixed bills. The system tracks them month by month automatically.": "Registra abbonamenti e fatture fisse. Il sistema li tiene traccia mese per mese automaticamente.",
  "Registering...": "Registrazione...",
  "Remaining": "Rimanente",
  "Remembered your password?": "Hai ricordato la password?",
  "Rent or mortgage": "Affitto o mutuo",
  "Rent received": "Affitto ricevuto",
  "Repeat password": "Ripeti la password",
  "Request new link": "Richiedi nuovo collegamento",
  "Reserve": "Riserva",
  "Reserve (savings goal)": "Riserva (obiettivo di risparmio)",
  "Reserve created successfully.": "Riserva creata con successo.",
  "Reserve name": "Nome della riserva",
  "Reserve name is required": "Il nome della riserva è obbligatorio",
  "Reserve → Wallet": "Riserva → Portafoglio",
  "Reserves": "Riserve",
  "Reserves and Wallets": "Riserve e Portafogli",
  "Reserves are your savings goals (Emergency Fund, Travel Fund, etc.). Wallets are where money is allocated (CDB, Savings, Treasury Bonds, Stocks). Configure them in Settings > Investments.": "Le riserve sono i tuoi obiettivi di risparmio (fondo di emergenza, fondo viaggio, ecc.). I portafogli sono dove viene allocato il denaro (CDB, risparmio, titoli di Stato, azioni). Configurali in Impostazioni > Investimenti.",
  "Reset password": "Reimposta la password",
  "Responsive dashboard on mobile": "Dashboard reattiva su dispositivi mobili",
  "Restaurants": "Ristoranti",
  "Retirement fund": "Fondo pensione",
  "Rideshare": "Ridesharing",
  "Salary": "Stipendio",
  "Salon and beauty": "Salone e bellezza",
  "Sat": "Sab",
  "Save": "Salva",
  "Save accumulated": "Salva importo accumulato",
  "Save category": "Salva categoria",
  "Save changes": "Salva modifiche",
  "Save new password": "Salva la nuova password",
  "Saving...": "Salvataggio...",
  "Savings account": "Conto di risparmio",
  "Savings goals: Emergency Fund, Travel Fund, Long-term Fund, High-value Purchase, etc.": "Obiettivi di risparmio: Fondo di emergenza, Fondo di viaggio, Fondo a lungo termine, Acquisto di alto valore, ecc.",
  "School tuition": "Retta scolastica",
  "Sections": "Sezioni",
  "See it in action": "Guardalo in azione",
  "See some tips to get started with Financial Control.": "Consulta alcuni suggerimenti per iniziare con il controllo finanziario.",
  "Select a category": "Seleziona una categoria",
  "Select a reserve": "Seleziona una riserva",
  "Select a reserve...": "Seleziona una riserva...",
  "Select a wallet": "Seleziona un portafoglio",
  "Select a wallet...": "Seleziona un portafoglio...",
  "Select origin...": "Seleziona origine...",
  "Select source reserve": "Seleziona la riserva di origine",
  "Select source wallet": "Seleziona il portafoglio di origine",
  "Select the day": "Seleziona il giorno",
  "Select type: Reserve or Wallet": "Seleziona il tipo: Riserva o Portafoglio",
  "Select...": "Seleziona...",
  "Send instructions": "Invia istruzioni",
  "Sending...": "Invio...",
  "Sep": "Set",
  "September": "Settembre",
  "Set a future deadline for the goal": "Stabilisci una scadenza futura per l'obiettivo",
  "Set financial goals, with or without a deadline, and track your progress.": "Stabilisci obiettivi finanziari, con o senza scadenza, e monitora i tuoi progressi.",
  "Set goals with target amount and deadline. Track visual progress directly on the dashboard.": "Stabilisci obiettivi con importo target e scadenza. Tieni traccia dei progressi visivi direttamente sulla dashboard.",
  "Set up fixed monthly contributions or a percentage of monthly income.": "Imposta versamenti mensili fissi o una percentuale delle entrate mensili.",
  "Settings": "Impostazioni",
  "Settings > Categories": "Impostazioni > Categorie",
  "Settings > Investments": "Impostazioni > Investimenti",
  "Setup: Name, total limit, closing and due dates. Optional: last 4 digits.": "Configurazione: nome, limite totale, date di chiusura e scadenza. Facoltativo: ultime 4 cifre.",
  "Shopping cart": "Carrello della spesa",
  "Showing {shown} of {total} records": "Mostrati {shown} di {total} record",
  "Sign in": "Accedi",
  "Sign in to your account": "Accedi al tuo account",
  "Sign out": "Esci",
  "Sign up": "Registrati",
  "Sign up to manage your finances": "Iscriviti per gestire le tue finanze",
  "Signing in...": "Accesso...",
  "Simple and predictable.": "Semplice e prevedibile.",
  "Since this goal has no linked reserve, update the accumulated amount manually.": "Poiché questo obiettivo non ha una riserva collegata, aggiorna manualmente l'importo accumulato.",
  "Smith": "Smith",
  "Snacks and fast food": "Spuntini e fast food",
  "Software and apps": "Software e app",
  "Something went wrong": "Qualcosa è andato storto",
  "Start 2 free months": "Inizia con 2 mesi gratuiti",
  "Start for free": "Inizia gratuitamente",
  "Start free": "Inizia gratis",
  "Start with 2 months free. No hassle, no surprises.": "Inizia con 2 mesi gratuiti. Nessun problema, nessuna sorpresa.",
  "Starting...": "Avvio...",
  "Status": "Stato",
  "Still have questions? Contact support by email.": "Hai ancora domande? Contatta l'assistenza tramite e-mail.",
  "Stocks": "Azioni",
  "Storage": "Archiviazione",
  "Subscription": "Abbonamento",
  "Subscriptions": "Abbonamenti",
  "Summary": "Riepilogo",
  "Sun": "Dom",
  "Supermarket": "Supermercato",
  "Supplements": "Supplementi",
  "Switch between light and dark theme": "Passa dal tema chiaro a quello scuro e viceversa",
  "Switch between light and dark themes to reduce eye strain and stay in control day and night.": "Passa dai temi chiari a quelli scuri per ridurre l'affaticamento degli occhi e mantenere il controllo giorno e notte.",
  "Switch to dark theme whenever you prefer.": "Passa al tema scuro quando preferisci.",
  "Take control": "Prendi il controllo",
  "Target amount (R$)": "Importo target (R$)",
  "Target amount must be greater than zero": "L'importo target deve essere maggiore di zero",
  "Taxes and fees": "Tasse e commissioni",
  "The Annual Table is available only on PC or tablet. Use a device with a larger screen to access this feature.": "La Tabella annuale è disponibile solo su PC o tablet. Usa un dispositivo con uno schermo più grande per accedere a questa funzionalità.",
  "The platform is designed for your routine: mobile-optimized screens and dark theme for more comfortable reading at night.": "La piattaforma è progettata per la tua routine: schermate ottimizzate per dispositivi mobili e tema scuro per una lettura più confortevole di notte.",
  "The withdrawn amount will be added to your monthly balance": "L'importo prelevato verrà aggiunto al tuo saldo mensile",
  "There are overdue bill(s) with an open balance.": "Sono presenti fatture scadute con saldo aperto.",
  "There is no bill to pay on this card.": "Non vi è alcuna fattura da pagare su questa carta.",
  "This CPF is already registered": "Questo CPF è già registrato",
  "This email is already in use": "Questa email è già in uso",
  "This email is already registered": "Questa email è già registrata",
  "Thu": "Gio",
  "To report something, contact one of our developers: ALEF, HENRIQUE.": "Per segnalare qualcosa, contatta uno dei nostri sviluppatori: ALEF, HENRIQUE.",
  "Top 5 expenses by category": "Le prime 5 spese per categoria",
  "Total": "Totale",
  "Total contracted limit at the bank (not the available amount)": "Limite totale contrattato presso la banca (non l'importo disponibile)",
  "Total invested": "Totale investito",
  "Total invested in category": "Totale investito nella categoria",
  "Total limit (R$)": "Limite totale (R$)",
  "Total limit: R$ {amount}": "Limite totale: R$ {amount}",
  "Total to set aside this month:": "Totale da accantonare questo mese:",
  "Total to set aside:": "Totale da accantonare:",
  "Track available limit, closed bills, and spending by category. Never be surprised by your bill again.": "Tieni traccia del limite disponibile, delle fatture chiuse e della spesa per categoria. Non lasciarti mai più sorprendere dalla tua bolletta.",
  "Track income, expenses, credit cards, investments, and goals in a clean dashboard. Real data, clear view — no spreadsheets.": "Tieni traccia di entrate, spese, carte di credito, investimenti e obiettivi in ​​una dashboard pulita. Dati reali, visione chiara, senza fogli di calcolo.",
  "Track monthly bills, mark as paid to record expenses, and see the total to set aside this month.": "Tieni traccia delle fatture mensili, contrassegnale come pagate per registrare le spese e visualizza il totale da accantonare questo mese.",
  "Track your contributions": "Tieni traccia dei tuoi contributi",
  "Track your expenses": "Tieni traccia delle tue spese",
  "Track your finances anywhere with an interface adapted for smaller screens and touch navigation.": "Tieni traccia delle tue finanze ovunque con un'interfaccia adattata per schermi più piccoli e navigazione touch.",
  "Track your income": "Tieni traccia delle tue entrate",
  "Transaction date": "Data della transazione",
  "Transaction not found": "Transazione non trovata",
  "Transport": "Trasporto",
  "Travel fund": "Fondo di viaggio",
  "Treasury bonds": "Titoli di Stato",
  "Trends": "Tendenze",
  "Trial end": "Fine della prova",
  "Trialing": "In prova",
  "Try again": "Riprova",
  "Tue": "Mar",
  "Type": "Tipo",
  "Unable to continue at the moment.": "Impossibile continuare al momento.",
  "Unauthorized": "Non autorizzato",
  "Unexpected error": "Errore imprevisto",
  "Unexpected error processing subscription.": "Errore imprevisto durante l'elaborazione dell'abbonamento.",
  "Unpaid": "Non pagato",
  "Update card": "Aggiorna carta",
  "Use cash balance": "Usa il saldo in contanti",
  "User": "Utente",
  "User not found": "Utente non trovato",
  "Variable": "Variabile",
  "Variable expenses": "Spese variabili",
  "Video": "Video",
  "Video streaming": "Streaming video",
  "View": "Visualizza",
  "View subscription": "Visualizza l'abbonamento",
  "Visual progress": "Progresso visivo",
  "Wallet": "Portafoglio",
  "Wallet (where money is allocated)": "Portafoglio (dove viene allocato il denaro)",
  "Wallets": "Portafogli",
  "Water": "Acqua",
  "Water bill": "Bolletta dell'acqua",
  "We are always working to improve.": "Lavoriamo sempre per migliorare.",
  "We received a request to reset your account password. If this was you, click the button below. The link expires soon.": "Abbiamo ricevuto una richiesta per reimpostare la password del tuo account. Se eri tu, fai clic sul pulsante qui sotto. Il collegamento scade a breve.",
  "Wed": "Mer",
  "Welcome to Logos Finance": "Benvenuti in Logos Finance",
  "Welcome, {name}": "Benvenuto, {name}",
  "Welcome, {name}!": "Benvenuto, {name}!",
  "Wellness": "Benessere",
  "What happens after the 2 free months?": "Cosa succede dopo i 2 mesi gratuiti?",
  "Where money is allocated: CDB, Savings, Treasury Bonds, Stocks, etc.": "Dove viene allocato il denaro: CDB, risparmio, titoli di Stato, azioni, ecc.",
  "Work lunch": "Pranzo di lavoro",
  "Year": "Anno",
  "Yes, Logos Finance is fully responsive and works on smartphones, tablets, and computers. Access it in the browser on any device without installing anything.": "Sì, Logos Finance è completamente reattivo e funziona su smartphone, tablet e computer. Accedi al browser su qualsiasi dispositivo senza installare nulla.",
  "Yes, a card is required at signup to activate the trial. But there is no charge for the first 2 months. The first charge happens only after the free period ends.": "Sì, è necessaria una carta al momento dell'iscrizione per attivare la prova. Ma per i primi 2 mesi non ci sono costi. Il primo addebito avviene solo al termine del periodo gratuito.",
  "Yes, cancel anytime with no penalty or fee. When you cancel, access continues until the end of the paid period. There is no minimum commitment.": "Sì, puoi annullare in qualsiasi momento senza alcuna penalità o commissione. Quando annulli, l'accesso continua fino alla fine del periodo pagato. Non esiste un impegno minimo.",
  "Yes, debit from cash": "Sì, addebito in contanti",
  "Yields": "Rendimenti",
  "You do not have any goals yet.": "Non hai ancora alcun obiettivo.",
  "You do not have any investments yet": "Non hai ancora alcun investimento",
  "You need to save {amount} per month to reach the target by {deadline}.": "Devi risparmiare {amount} al mese per raggiungere l'obiettivo entro {deadline}.",
  "You register your cards with total limit and closing/due dates. The system tracks spending in real time, controls available limit, and helps you follow each bill amount.": "Registri le tue carte con limite totale e date di chiusura/scadenza. Il sistema monitora le spese in tempo reale, controlla il limite disponibile e ti aiuta a seguire l'importo di ogni fattura.",
  "Your account was created successfully. You can now organize income, expenses, and investments in one place.": "Il tuo account è stato creato con successo. Ora puoi organizzare entrate, spese e investimenti in un unico posto.",
  "Your dashboard works great on mobile and in dark mode.": "La tua dashboard funziona perfettamente su dispositivi mobili e in modalità scura.",
  "Your data is stored securely and is not shared with third parties. Only you have access to your financial information.": "I tuoi dati sono archiviati in modo sicuro e non vengono condivisi con terze parti. Solo tu hai accesso alle tue informazioni finanziarie.",
  "Your data stays yours": "I tuoi dati restano tuoi",
  "Your name": "Il tuo nome",
  "Your recurring bills are between 60% and 70% of income. Watch closely to keep budget flexibility.": "Le tue bollette ricorrenti rappresentano tra il 60% e il 70% delle tue entrate. Tienile sotto controllo per mantenere flessibilità nel budget.",
  "Your recurring bills consume 70% or more of your income. Review spending and reserves to protect your financial balance.": "Le tue bollette ricorrenti assorbono il 70% o più delle tue entrate. Rivedi spese e riserve per proteggere il tuo equilibrio finanziario.",
  "Your subscription is set to cancel at the end of the current period.": "Il tuo abbonamento verrà annullato alla fine del periodo corrente.",
  "available": "disponibile",
  "balance": "saldo",
  "commitment fee": "costo di impegno",
  "free to try": "di prova gratuita",
  "less than a minute": "meno di un minuto",
  "login": "login",
  "of": "di",
  "of your finances": "delle tue finanze",
  "open (due {dueDate}, closing {closingDate})": "aperto (scadenza {dueDate}, chiusura {closingDate})",
  "per month after trial": "al mese dopo la prova",
  "personally.": "personalmente.",
  "privacy for your data": "privacy per i tuoi dati",
  "with contribution": "con versamento",
  "with entry": "con registrazione",
  "withdrawal": "prelievo",
  "without using cash": "senza utilizzare contanti",
  "you@email.com": "you@email.com",
  "your finances?": "le tue finanze?",
  "{cardName}{lastFour}: R$ {amount} (due {dueDate}, closing {closingDate})": "{cardName}{lastFour}: R$ {amount} (scadenza {dueDate}, chiusura {closingDate})",
  "{count} days": "{count} giorni",
  "{count} hours": "{count} ore",
  "{count} minutes": "{count} minuti",
  "{hours} and {minutes} min": "{hours} e {minutes} min",
  "{month} {year}": "{month} {year}",
  "{percentage}% of income": "{percentage}% delle entrate",
  "{percent}% of total": "{percent}% del totale",
  "{remaining} remaining. After that, the monthly charge will be made to the card on file.": "{remaining} rimanenti. Successivamente, l'addebito mensile verrà effettuato sulla carta in archivio.",
  "© {year} {appName}. All rights reserved.": "© {year} {appName}. Tutti i diritti riservati.",
  "••••••••": "••••••••",
  "Italiano": "Italiano"
};
